[2025-02-25T09:48:44.832+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-25T09:48:44.901+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-25T09:48:44.905+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:48:45.022+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-14 00:00:00+00:00
[2025-02-25T09:48:45.064+0000] {standard_task_runner.py:57} INFO - Started process 344 to run task
[2025-02-25T09:48:45.104+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpcybyo3eb']
[2025-02-25T09:48:45.115+0000] {standard_task_runner.py:85} INFO - Job 58: Subtask store_raw_data_in_hdfs
[2025-02-25T09:48:45.574+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:48:46.136+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-02-25T09:49:38.058+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:49:38.323+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250114T000000, start_date=20250225T094844, end_date=20250225T094938
[2025-02-25T09:49:38.579+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:49:38.750+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:10:58.317+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:10:58.334+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:10:58.335+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:10:58.362+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-14 00:00:00+00:00
[2025-02-26T20:10:58.372+0000] {standard_task_runner.py:57} INFO - Started process 541 to run task
[2025-02-26T20:10:58.377+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpoqhitgui']
[2025-02-26T20:10:58.381+0000] {standard_task_runner.py:85} INFO - Job 64: Subtask store_raw_data_in_hdfs
[2025-02-26T20:10:58.457+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [running]> on host e304e68c626e
[2025-02-26T20:10:58.581+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-02-26T20:10:58.604+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 84, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-26T20:10:58.619+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250114T000000, start_date=20250226T201058, end_date=20250226T201058
[2025-02-26T20:10:58.639+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 64 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 541)
[2025-02-26T20:10:58.671+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:10:58.717+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:30:32.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:30:32.825+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:30:32.831+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:30:32.888+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-14 00:00:00+00:00
[2025-02-26T20:30:32.913+0000] {standard_task_runner.py:57} INFO - Started process 1825 to run task
[2025-02-26T20:30:32.911+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp6uc_ocf1']
[2025-02-26T20:30:32.931+0000] {standard_task_runner.py:85} INFO - Job 180: Subtask store_raw_data_in_hdfs
[2025-02-26T20:30:33.192+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [running]> on host c96a1011f5a3
[2025-02-26T20:30:33.593+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-02-26T20:31:03.816+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:31:03.857+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250114T000000, start_date=20250226T203032, end_date=20250226T203103
[2025-02-26T20:31:04.015+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:31:04.106+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:40:15.215+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:40:15.240+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:40:15.241+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:40:15.279+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-14 00:00:00+00:00
[2025-02-26T20:40:15.295+0000] {standard_task_runner.py:57} INFO - Started process 1287 to run task
[2025-02-26T20:40:15.336+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '294', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp_28pnap2']
[2025-02-26T20:40:15.342+0000] {standard_task_runner.py:85} INFO - Job 294: Subtask store_raw_data_in_hdfs
[2025-02-26T20:40:15.516+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-14T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:40:15.864+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-02-26T20:40:55.688+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:40:55.754+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250114T000000, start_date=20250226T204015, end_date=20250226T204055
[2025-02-26T20:40:55.838+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:40:55.897+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
