[2025-02-25T09:50:59.626+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-25T09:50:59.698+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-25T09:50:59.709+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:50:59.797+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-14 00:00:00+00:00
[2025-02-25T09:50:59.816+0000] {standard_task_runner.py:57} INFO - Started process 1171 to run task
[2025-02-25T09:50:59.832+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpq9wwtngh']
[2025-02-25T09:50:59.841+0000] {standard_task_runner.py:85} INFO - Job 123: Subtask store_raw_data_in_hdfs
[2025-02-25T09:51:00.118+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:51:00.834+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-25T09:51:41.214+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:51:41.258+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250214T000000, start_date=20250225T095059, end_date=20250225T095141
[2025-02-25T09:51:41.368+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:51:41.417+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:46:40.543+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-26T20:46:40.618+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-26T20:46:40.619+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:46:41.174+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-14 00:00:00+00:00
[2025-02-26T20:46:41.201+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '417', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpdrunw9jy']
[2025-02-26T20:46:41.207+0000] {standard_task_runner.py:85} INFO - Job 417: Subtask store_raw_data_in_hdfs
[2025-02-26T20:46:41.194+0000] {standard_task_runner.py:57} INFO - Started process 3000 to run task
[2025-02-26T20:46:41.376+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:46:41.826+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-26T20:47:15.257+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:47:15.287+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250214T000000, start_date=20250226T204640, end_date=20250226T204715
[2025-02-26T20:47:15.371+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:47:15.414+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:56:09.553+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-27T14:56:09.567+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [queued]>
[2025-02-27T14:56:09.568+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:56:09.586+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-14 00:00:00+00:00
[2025-02-27T14:56:09.595+0000] {standard_task_runner.py:57} INFO - Started process 471 to run task
[2025-02-27T14:56:09.600+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-14T00:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp96uyybze']
[2025-02-27T14:56:09.604+0000] {standard_task_runner.py:85} INFO - Job 96: Subtask store_raw_data_in_hdfs
[2025-02-27T14:56:09.688+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-14T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:56:09.834+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-14T00:00:00+00:00'
[2025-02-27T14:56:09.850+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:56:09.866+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250214T000000, start_date=20250227T145609, end_date=20250227T145609
[2025-02-27T14:56:09.882+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 96 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 471)
[2025-02-27T14:56:09.896+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:56:09.926+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
