[2025-02-24T16:17:39.142+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_mapreduce_dag.run_mapreduce_job manual__2025-02-24T16:17:25.212956+00:00 [queued]>
[2025-02-24T16:17:39.152+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_mapreduce_dag.run_mapreduce_job manual__2025-02-24T16:17:25.212956+00:00 [queued]>
[2025-02-24T16:17:39.153+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-24T16:17:39.169+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce_job> on 2025-02-24 16:17:25.212956+00:00
[2025-02-24T16:17:39.178+0000] {standard_task_runner.py:57} INFO - Started process 2920 to run task
[2025-02-24T16:17:39.182+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_mapreduce_dag', 'run_mapreduce_job', 'manual__2025-02-24T16:17:25.212956+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpvczkkmt4']
[2025-02-24T16:17:39.185+0000] {standard_task_runner.py:85} INFO - Job 17: Subtask run_mapreduce_job
[2025-02-24T16:17:39.243+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_mapreduce_dag.run_mapreduce_job manual__2025-02-24T16:17:25.212956+00:00 [running]> on host 94f70d9be3b1
[2025-02-24T16:17:39.412+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_mapreduce_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-24T16:17:25.212956+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-24T16:17:25.212956+00:00'
[2025-02-24T16:17:39.421+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-24T16:17:39.423+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode hdfs dfs -rm -r /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=24 || true &&         docker exec -i -u root namenode hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar             -file /mnt/hadoop_data/mapper.py -mapper "python3 mapper.py"             -file /mnt/hadoop_data/reducer.py -reducer "python3 reducer.py"             -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=24/coingecko_raw.json             -output /user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=24\n        ']
[2025-02-24T16:17:39.440+0000] {subprocess.py:86} INFO - Output:
[2025-02-24T16:17:41.703+0000] {subprocess.py:93} INFO - rm: `/user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=24': No such file or directory
[2025-02-24T16:17:43.247+0000] {subprocess.py:93} INFO - 2025-02-24 16:17:43,245 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
[2025-02-24T16:17:44.689+0000] {subprocess.py:93} INFO - packageJobJar: [/mnt/hadoop_data/mapper.py, /mnt/hadoop_data/reducer.py] [] /tmp/streamjob4170680165065165352.jar tmpDir=null
[2025-02-24T16:17:44.702+0000] {subprocess.py:93} INFO - Exception in thread "main" java.io.IOException: expanding mapper.py would create file outside of /.
[2025-02-24T16:17:44.703+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:199)
[2025-02-24T16:17:44.704+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.StreamJob.submitAndMonitorJob(StreamJob.java:1011)
[2025-02-24T16:17:44.705+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.StreamJob.run(StreamJob.java:135)
[2025-02-24T16:17:44.706+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:76)
[2025-02-24T16:17:44.706+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:90)
[2025-02-24T16:17:44.707+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.HadoopStreaming.main(HadoopStreaming.java:50)
[2025-02-24T16:17:44.708+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-02-24T16:17:44.708+0000] {subprocess.py:93} INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2025-02-24T16:17:44.709+0000] {subprocess.py:93} INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-02-24T16:17:44.710+0000] {subprocess.py:93} INFO - 	at java.lang.reflect.Method.invoke(Method.java:498)
[2025-02-24T16:17:44.710+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.run(RunJar.java:323)
[2025-02-24T16:17:44.711+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.util.RunJar.main(RunJar.java:236)
[2025-02-24T16:17:45.083+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-24T16:17:45.116+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-24T16:17:45.129+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_mapreduce_dag, task_id=run_mapreduce_job, execution_date=20250224T161725, start_date=20250224T161739, end_date=20250224T161745
[2025-02-24T16:17:45.157+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 17 for task run_mapreduce_job (Bash command failed. The command returned a non-zero exit code 1.; 2920)
[2025-02-24T16:17:45.197+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-24T16:17:45.216+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
