[2025-02-25T09:50:59.343+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-25T09:50:59.370+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-25T09:50:59.376+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:50:59.503+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-03 00:00:00+00:00
[2025-02-25T09:50:59.518+0000] {standard_task_runner.py:57} INFO - Started process 1160 to run task
[2025-02-25T09:50:59.526+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-03T00:00:00+00:00', '--job-id', '120', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpkpumnn61']
[2025-02-25T09:50:59.536+0000] {standard_task_runner.py:85} INFO - Job 120: Subtask store_raw_data_in_hdfs
[2025-02-25T09:50:59.806+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:51:00.568+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T00:00:00+00:00'
[2025-02-25T09:51:41.237+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:51:41.278+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250203T000000, start_date=20250225T095059, end_date=20250225T095141
[2025-02-25T09:51:41.389+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:51:41.429+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:44:22.976+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-26T20:44:22.990+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-26T20:44:22.991+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:44:23.008+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-03 00:00:00+00:00
[2025-02-26T20:44:23.017+0000] {standard_task_runner.py:57} INFO - Started process 2304 to run task
[2025-02-26T20:44:23.021+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-03T00:00:00+00:00', '--job-id', '364', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpn3jrtogg']
[2025-02-26T20:44:23.025+0000] {standard_task_runner.py:85} INFO - Job 364: Subtask store_raw_data_in_hdfs
[2025-02-26T20:44:23.088+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:44:23.205+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T00:00:00+00:00'
[2025-02-26T20:44:30.472+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:44:30.490+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250203T000000, start_date=20250226T204422, end_date=20250226T204430
[2025-02-26T20:44:30.554+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:44:30.578+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:56:02.473+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-27T14:56:02.510+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [queued]>
[2025-02-27T14:56:02.512+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:56:02.628+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-03 00:00:00+00:00
[2025-02-27T14:56:02.657+0000] {standard_task_runner.py:57} INFO - Started process 449 to run task
[2025-02-27T14:56:02.679+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-03T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpgfz8109l']
[2025-02-27T14:56:02.713+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask store_raw_data_in_hdfs
[2025-02-27T14:56:03.001+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-03T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:56:03.339+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-03T00:00:00+00:00'
[2025-02-27T14:56:03.398+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:56:03.445+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250203T000000, start_date=20250227T145602, end_date=20250227T145603
[2025-02-27T14:56:03.490+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 83 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 449)
[2025-02-27T14:56:03.568+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:56:04.713+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
