[2025-02-25T09:52:02.628+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-25T09:52:02.657+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-25T09:52:02.658+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:52:02.686+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-19 00:00:00+00:00
[2025-02-25T09:52:02.702+0000] {standard_task_runner.py:57} INFO - Started process 1494 to run task
[2025-02-25T09:52:02.714+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '135', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpkkps6_rb']
[2025-02-25T09:52:02.723+0000] {standard_task_runner.py:85} INFO - Job 135: Subtask store_raw_data_in_hdfs
[2025-02-25T09:52:02.843+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:52:03.112+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-25T09:52:27.416+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:52:27.441+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250219T000000, start_date=20250225T095202, end_date=20250225T095227
[2025-02-25T09:52:29.765+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:52:29.795+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:46:43.873+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-26T20:46:43.906+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-26T20:46:43.917+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:46:43.997+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-19 00:00:00+00:00
[2025-02-26T20:46:44.035+0000] {standard_task_runner.py:57} INFO - Started process 3022 to run task
[2025-02-26T20:46:44.049+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '421', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpvty12vhw']
[2025-02-26T20:46:44.103+0000] {standard_task_runner.py:85} INFO - Job 421: Subtask store_raw_data_in_hdfs
[2025-02-26T20:46:44.416+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:46:44.843+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-26T20:47:18.439+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:47:18.462+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250219T000000, start_date=20250226T204643, end_date=20250226T204718
[2025-02-26T20:47:18.577+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:47:18.743+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:56:28.911+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-27T14:56:29.024+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [queued]>
[2025-02-27T14:56:29.084+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:56:29.328+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-19 00:00:00+00:00
[2025-02-27T14:56:29.557+0000] {standard_task_runner.py:57} INFO - Started process 527 to run task
[2025-02-27T14:56:29.545+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-19T00:00:00+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpuaymsyc7']
[2025-02-27T14:56:29.572+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask store_raw_data_in_hdfs
[2025-02-27T14:56:28.232+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-19T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:56:28.869+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-19T00:00:00+00:00'
[2025-02-27T14:56:28.960+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:56:29.144+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250219T000000, start_date=20250227T145628, end_date=20250227T145629
[2025-02-27T14:56:29.230+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 112 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 527)
[2025-02-27T14:56:29.312+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:56:29.479+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
