[2025-02-25T09:52:02.274+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-25T09:52:02.298+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-25T09:52:02.299+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:52:02.349+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-17 00:00:00+00:00
[2025-02-25T09:52:02.380+0000] {standard_task_runner.py:57} INFO - Started process 1491 to run task
[2025-02-25T09:52:02.398+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '134', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmp2btzpoi_']
[2025-02-25T09:52:02.416+0000] {standard_task_runner.py:85} INFO - Job 134: Subtask store_raw_data_in_hdfs
[2025-02-25T09:52:02.586+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:52:02.811+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-25T09:52:27.221+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:52:27.272+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250217T000000, start_date=20250225T095202, end_date=20250225T095227
[2025-02-25T09:52:29.785+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:52:29.815+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:46:44.339+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-26T20:46:44.409+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-26T20:46:44.416+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:46:44.516+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-17 00:00:00+00:00
[2025-02-26T20:46:44.527+0000] {standard_task_runner.py:57} INFO - Started process 3024 to run task
[2025-02-26T20:46:44.564+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '419', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpilkkube8']
[2025-02-26T20:46:44.591+0000] {standard_task_runner.py:85} INFO - Job 419: Subtask store_raw_data_in_hdfs
[2025-02-26T20:46:44.843+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:46:45.207+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-26T20:47:19.177+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:47:19.246+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250217T000000, start_date=20250226T204644, end_date=20250226T204719
[2025-02-26T20:47:19.462+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:47:19.549+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:56:27.497+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-27T14:56:27.563+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [queued]>
[2025-02-27T14:56:27.569+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:56:28.131+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-17 00:00:00+00:00
[2025-02-27T14:56:28.153+0000] {standard_task_runner.py:57} INFO - Started process 526 to run task
[2025-02-27T14:56:28.184+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-17T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpkpzdl_vp']
[2025-02-27T14:56:28.192+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask store_raw_data_in_hdfs
[2025-02-27T14:56:28.655+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-17T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:56:29.440+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-17T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-17T00:00:00+00:00'
[2025-02-27T14:56:29.589+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:56:29.205+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250217T000000, start_date=20250227T145627, end_date=20250227T145629
[2025-02-27T14:56:28.264+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 526)
[2025-02-27T14:56:28.383+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:56:29.060+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
