[2025-02-25T09:50:57.377+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-25T09:50:57.422+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-25T09:50:57.428+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:50:57.508+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-08 00:00:00+00:00
[2025-02-25T09:50:57.539+0000] {standard_task_runner.py:57} INFO - Started process 1143 to run task
[2025-02-25T09:50:57.552+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmph6s4tmvc']
[2025-02-25T09:50:57.568+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask store_raw_data_in_hdfs
[2025-02-25T09:50:57.851+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:50:58.408+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-25T09:51:38.672+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:51:38.818+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250208T000000, start_date=20250225T095057, end_date=20250225T095138
[2025-02-25T09:51:39.139+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:51:39.313+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:45:23.265+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-26T20:45:23.281+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-26T20:45:23.282+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:45:23.306+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-08 00:00:00+00:00
[2025-02-26T20:45:23.316+0000] {standard_task_runner.py:57} INFO - Started process 2557 to run task
[2025-02-26T20:45:23.322+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp_waaef_d']
[2025-02-26T20:45:23.328+0000] {standard_task_runner.py:85} INFO - Job 381: Subtask store_raw_data_in_hdfs
[2025-02-26T20:45:23.402+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:45:23.542+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-26T20:45:30.656+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:45:30.672+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250208T000000, start_date=20250226T204523, end_date=20250226T204530
[2025-02-26T20:45:30.727+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:45:30.757+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:56:06.328+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-27T14:56:06.421+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [queued]>
[2025-02-27T14:56:06.428+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:56:06.499+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-08 00:00:00+00:00
[2025-02-27T14:56:06.532+0000] {standard_task_runner.py:57} INFO - Started process 461 to run task
[2025-02-27T14:56:06.567+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-08T00:00:00+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmphpgjvs4h']
[2025-02-27T14:56:06.591+0000] {standard_task_runner.py:85} INFO - Job 91: Subtask store_raw_data_in_hdfs
[2025-02-27T14:56:06.835+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-08T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:56:07.147+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-08T00:00:00+00:00'
[2025-02-27T14:56:07.213+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:56:07.293+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250208T000000, start_date=20250227T145606, end_date=20250227T145607
[2025-02-27T14:56:07.380+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 91 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 461)
[2025-02-27T14:56:07.422+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:56:07.532+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
